namespace Dominion.Core.Dto.EEOC.EEO1.Comp1
{
    public class Eeo1Comp1LocationJobCategoryDemographicsDto
    {
        public string Location { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string County { get; set; }
        public string UnitNumber { get; set; }
        public bool IsHeadquarters { get; set; }
        public int LocationCount { get; set; }
        public int EeocJobCategoryId { get; set; }
        public int ExecutiveLevel_Hispanic_Male_Count { get; set; }
        public int ExecutiveLevel_Hispanic_Female_Count { get; set; }
        public int ExecutiveLevel_White_Male_Count { get; set; }
        public int ExecutiveLevel_Black_Male_Count { get; set; }
        public int ExecutiveLevel_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int ExecutiveLevel_Asian_Male_Count { get; set; }
        public int ExecutiveLevel_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int ExecutiveLevel_TwoOrMoreRaces_Male_Count { get; set; }
        public int ExecutiveLevel_White_Female_Count { get; set; }
        public int ExecutiveLevel_Black_Female_Count { get; set; }
        public int ExecutiveLevel_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int ExecutiveLevel_Asian_Female_Count { get; set; }
        public int ExecutiveLevel_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int ExecutiveLevel_TwoOrMoreRaces_Female_Count { get; set; }
        public int ExecutiveLevel_Total { get; set; }
        public int MidLevel_Hispanic_Male_Count { get; set; }
        public int MidLevel_Hispanic_Female_Count { get; set; }
        public int MidLevel_White_Male_Count { get; set; }
        public int MidLevel_Black_Male_Count { get; set; }
        public int MidLevel_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int MidLevel_Asian_Male_Count { get; set; }
        public int MidLevel_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int MidLevel_TwoOrMoreRaces_Male_Count { get; set; }
        public int MidLevel_White_Female_Count { get; set; }
        public int MidLevel_Black_Female_Count { get; set; }
        public int MidLevel_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int MidLevel_Asian_Female_Count { get; set; }
        public int MidLevel_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int MidLevel_TwoOrMoreRaces_Female_Count { get; set; }
        public int MidLevel_Total { get; set; }
        public int Professionals_Hispanic_Male_Count { get; set; }
        public int Professionals_Hispanic_Female_Count { get; set; }
        public int Professionals_White_Male_Count { get; set; }
        public int Professionals_Black_Male_Count { get; set; }
        public int Professionals_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int Professionals_Asian_Male_Count { get; set; }
        public int Professionals_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int Professionals_TwoOrMoreRaces_Male_Count { get; set; }
        public int Professionals_White_Female_Count { get; set; }
        public int Professionals_Black_Female_Count { get; set; }
        public int Professionals_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int Professionals_Asian_Female_Count { get; set; }
        public int Professionals_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int Professionals_TwoOrMoreRaces_Female_Count { get; set; }
        public int Professionals_Total { get; set; }
        public int Technicians_Hispanic_Male_Count { get; set; }
        public int Technicians_Hispanic_Female_Count { get; set; }
        public int Technicians_White_Male_Count { get; set; }
        public int Technicians_Black_Male_Count { get; set; }
        public int Technicians_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int Technicians_Asian_Male_Count { get; set; }
        public int Technicians_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int Technicians_TwoOrMoreRaces_Male_Count { get; set; }
        public int Technicians_White_Female_Count { get; set; }
        public int Technicians_Black_Female_Count { get; set; }
        public int Technicians_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int Technicians_Asian_Female_Count { get; set; }
        public int Technicians_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int Technicians_TwoOrMoreRaces_Female_Count { get; set; }
        public int Technicians_Total { get; set; }
        public int SalesWorkers_Hispanic_Male_Count { get; set; }
        public int SalesWorkers_Hispanic_Female_Count { get; set; }
        public int SalesWorkers_White_Male_Count { get; set; }
        public int SalesWorkers_Black_Male_Count { get; set; }
        public int SalesWorkers_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int SalesWorkers_Asian_Male_Count { get; set; }
        public int SalesWorkers_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int SalesWorkers_TwoOrMoreRaces_Male_Count { get; set; }
        public int SalesWorkers_White_Female_Count { get; set; }
        public int SalesWorkers_Black_Female_Count { get; set; }
        public int SalesWorkers_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int SalesWorkers_Asian_Female_Count { get; set; }
        public int SalesWorkers_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int SalesWorkers_TwoOrMoreRaces_Female_Count { get; set; }
        public int SalesWorkers_Total { get; set; }
        public int AdministrativeSupport_Hispanic_Male_Count { get; set; }
        public int AdministrativeSupport_Hispanic_Female_Count { get; set; }
        public int AdministrativeSupport_White_Male_Count { get; set; }
        public int AdministrativeSupport_Black_Male_Count { get; set; }
        public int AdministrativeSupport_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int AdministrativeSupport_Asian_Male_Count { get; set; }
        public int AdministrativeSupport_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int AdministrativeSupport_TwoOrMoreRaces_Male_Count { get; set; }
        public int AdministrativeSupport_White_Female_Count { get; set; }
        public int AdministrativeSupport_Black_Female_Count { get; set; }
        public int AdministrativeSupport_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int AdministrativeSupport_Asian_Female_Count { get; set; }
        public int AdministrativeSupport_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int AdministrativeSupport_TwoOrMoreRaces_Female_Count { get; set; }
        public int AdministrativeSupport_Total { get; set; }
        public int CraftWorkers_Hispanic_Male_Count { get; set; }
        public int CraftWorkers_Hispanic_Female_Count { get; set; }
        public int CraftWorkers_White_Male_Count { get; set; }
        public int CraftWorkers_Black_Male_Count { get; set; }
        public int CraftWorkers_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int CraftWorkers_Asian_Male_Count { get; set; }
        public int CraftWorkers_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int CraftWorkers_TwoOrMoreRaces_Male_Count { get; set; }
        public int CraftWorkers_White_Female_Count { get; set; }
        public int CraftWorkers_Black_Female_Count { get; set; }
        public int CraftWorkers_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int CraftWorkers_Asian_Female_Count { get; set; }
        public int CraftWorkers_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int CraftWorkers_TwoOrMoreRaces_Female_Count { get; set; }
        public int CraftWorkers_Total { get; set; }
        public int Operatives_Hispanic_Male_Count { get; set; }
        public int Operatives_Hispanic_Female_Count { get; set; }
        public int Operatives_White_Male_Count { get; set; }
        public int Operatives_Black_Male_Count { get; set; }
        public int Operatives_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int Operatives_Asian_Male_Count { get; set; }
        public int Operatives_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int Operatives_TwoOrMoreRaces_Male_Count { get; set; }
        public int Operatives_White_Female_Count { get; set; }
        public int Operatives_Black_Female_Count { get; set; }
        public int Operatives_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int Operatives_Asian_Female_Count { get; set; }
        public int Operatives_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int Operatives_TwoOrMoreRaces_Female_Count { get; set; }
        public int Operatives_Total { get; set; }
        public int LaborersAndHelpers_Hispanic_Male_Count { get; set; }
        public int LaborersAndHelpers_Hispanic_Female_Count { get; set; }
        public int LaborersAndHelpers_White_Male_Count { get; set; }
        public int LaborersAndHelpers_Black_Male_Count { get; set; }
        public int LaborersAndHelpers_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int LaborersAndHelpers_Asian_Male_Count { get; set; }
        public int LaborersAndHelpers_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int LaborersAndHelpers_TwoOrMoreRaces_Male_Count { get; set; }
        public int LaborersAndHelpers_White_Female_Count { get; set; }
        public int LaborersAndHelpers_Black_Female_Count { get; set; }
        public int LaborersAndHelpers_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int LaborersAndHelpers_Asian_Female_Count { get; set; }
        public int LaborersAndHelpers_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int LaborersAndHelpers_TwoOrMoreRaces_Female_Count { get; set; }
        public int LaborersAndHelpers_Total { get; set; }
        public int ServiceWorkers_Hispanic_Male_Count { get; set; }
        public int ServiceWorkers_Hispanic_Female_Count { get; set; }
        public int ServiceWorkers_White_Male_Count { get; set; }
        public int ServiceWorkers_Black_Male_Count { get; set; }
        public int ServiceWorkers_NativeHawaiian_OtherPacificIslander_Male_Count { get; set; }
        public int ServiceWorkers_Asian_Male_Count { get; set; }
        public int ServiceWorkers_AmericanIndian_Or_AlaskaNative_Male_Count { get; set; }
        public int ServiceWorkers_TwoOrMoreRaces_Male_Count { get; set; }
        public int ServiceWorkers_White_Female_Count { get; set; }
        public int ServiceWorkers_Black_Female_Count { get; set; }
        public int ServiceWorkers_NativeHawaiian_OtherPacificIslander_Female_Count { get; set; }
        public int ServiceWorkers_Asian_Female_Count { get; set; }
        public int ServiceWorkers_AmericanIndian_Or_AlaskaNative_Female_Count { get; set; }
        public int ServiceWorkers_TwoOrMoreRaces_Female_Count { get; set; }
        public int ServiceWorkers_Total { get; set; }
        public int LocationEmployeeTotal { get; set; }
    }
}
