import { DaySchedule } from './day-schedule.model';

export interface ClockTimeCard {
        rowTypeId: number, 
        dayAmount: number
        day: String, 
        date: String, 
        in: String, 
        inRaw: String, 
        inDateTime: Date, 
        inEmployeePunchId: String, 
        inClockClientLunchId: String, 
        inTimeZoneId: String, 
        out: String, 
        outRaw: String, 
        outDateTime: Date, 
        outEmployeePunchId: String, 
        outClockClientLunchId: String, 
        outTimeZoneId: String, 
        in2: String, 
        in2Raw: String, 
        in2DateTime: Date, 
        in2EmployeePunchId: String, 
        in2ClockClientLunchId: String, 
        in2TimeZoneId: String, 
        out2: String, 
        out2Raw: String, 
        out2DateTime: Date, 
        out2EmployeePunchId: String, 
        out2ClockClientLunchId: String, 
        out2TimeZoneId: String, 
        hours: String, 
        hasRequestedPunch: Boolean, 
        exceptions: String, 
        notes: String, 
        dayScheduleDto: DaySchedule, 
        inHasException: Boolean,
        in2HasException: Boolean,
        outHasException: Boolean,
        out2HasException: Boolean,
        inIsMissing: Boolean,
        in2IsMissing: Boolean,
        outIsMissing: Boolean,
        out2IsMissing: Boolean,
        outUrl: String, 
        out2Url: String, 
        outHasUrl : Boolean,
        out2HasUrl : Boolean
}