using System;

namespace Dominion.Core.Dto.Payroll
{
    [Flags]
    public enum StateId: byte
    {
        Michigan = 1,
        Florida = 2,
        Alabama = 3,
        Alaska = 4,
        Arizona = 5,
        Arkansas = 6,
        California = 7,
        Colorado = 8,
        Connecticut = 9,
        Indiana = 10,
        Delaware = 11,
        DC = 12,
        Georgia = 14,
        Hawaii = 15,
        Idaho = 16,
        Illinois = 17,
        Iowa = 18,
        Kansas = 19,
        Kentucky = 20,
        Louisiana = 21,
        Maine = 22,
        Maryland = 23,
        Massachusetts = 24,
        Minnesota = 25,
        Mississippi = 26,
        Missouri = 27,
        Montana = 28,
        Nebraska = 29,
        Nevada = 30,
        NewHampshire = 31,
        NewJersey = 32,
        NewMexico = 33,
        NewYork = 34,
        NorthCarolina = 35,
        NorthDakota = 36,
        Ohio = 37,
        Oklahoma = 38,
        Oregon = 39,
        Pennsylvania = 40,
        RhodeIsland = 41,
        SouthCarolina = 42,
        SouthDakota = 43,
        Tennessee = 44,
        Texas = 45,
        Utah = 46,
        Vermont = 47,
        Virginia = 48,
        Washington = 49,
        WestVirginia = 50,
        Wisconsin = 51,
        Wyoming = 52
    }
}