using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Dominion.Core.Services.Api;
using Dominion.Core.Services.Interfaces;
using Dominion.LaborManagement.Service.Api;
using Dominion.LaborManagement.Service.Internal;
using Dominion.LaborManagement.Service.Internal.Providers;
using Dominion.Testing.Util.Common;
using Dominion.Testing.Util.Helpers.Prototyping;
using Moq;
using NUnit.Framework;

namespace Dominion.LaborManagement.Test.Service.XMLData
{
    /// <summary>
    /// Getting the job posts is functionality delegated to the database.  This test was only used to check the sql being generated by the service.
    /// </summary>
    [TestFixture]
    public class XMLDataServiceTests
    {
        private IndeedXMLDataService _service { get; set; }

        private IBusinessApiSession _session { get; set; }

        [SetUp]
        public void SetUp()
        {
            var fundamentals = new ProtoFundamentals(ConnStr.ConnectionString);
            var settings = PreConfiguredProtoApiSettings.PioneerResources_JayJohnson_Sys();
            _session = new ProtoApiSession(fundamentals, settings).BusinessApiSession;
            _service = new IndeedXMLDataService(_session);
            
        }

        
        [Test]
        public void Test_GetJobPostsForIndeed_Returns_Something()
        {
            Console.Write(System.Environment.MachineName);
            IEnumerable<IndeedXmlJobPost> posts = _service.GetJobPostsForIndeed();

            foreach (string item in posts.Select(x=>x.ClientEmail).Distinct())
                Console.WriteLine(item);

            Assert.AreNotEqual(0, posts.Count());
        }
    }
}
