export interface IEmployeeDependent {
    employeeDependentId: number,
	clientId: number,
    firstName: string,
    middleInitial: string,
    lastName: string,
    employeeId: number,
    unmaskedSocialSecurityNumber: string,
    maskedSocialSecurityNumber: string,
    unmaskedConfirmSocialSecurityNumber?: string,
    employeeDependentsRelationshipId?: number,
    relationship: string,
    gender: string,
    comments: string,
    birthDate?: Date,
    insertStatus: number,
    lastModifiedByDescription: string,
    lastModifiedDate?: Date,
    isAStudent: boolean,
    hasADisability: boolean,
    tobaccoUser: boolean,
    isSelected: boolean,
    primaryCarePhysician?: number,
    hasPcp: boolean,
    isChild: boolean,
    isSpouse: boolean,
    isInactive: boolean,
    inactiveDate?: Date,
    isDirty?: boolean,
    hovered?: boolean
}
export interface IEmployeeDependentRelationship {
    employeeDependentsRelationshipId: number,
    isChild: boolean,
    isSpouse: boolean,
    description: string,
}