export interface IEmployeeDependent {
    employeeDependentId: number,
	clientId: number,
    firstName: string,
    middleInitial: string,
    lastName: string,
    employeeId: number,
    unmaskedSocialSecurityNumber: string,
    maskedSocialSecurityNumber: string,
    unmaskedConfirmSocialSecurityNumber?: string,
    relationship: string,
    gender: string,
    comments: string,
    birthDate: Date | null,
    insertStatus: number,
    lastModifiedByDescription: string,
    lastModifiedDate: Date,
    isAStudent: boolean,
    hasADisability: boolean,
    tobaccoUser: boolean,
    isSelected: boolean,
    primaryCarePhysician: number,
    hasPcp: boolean,
    employeeDependentsRelationshipId: number | null,
    isChild: boolean,
    isSpouse: boolean,
    isInactive: boolean,
    inactiveDate: Date | null
}
export interface IEmployeeDependentRelationship {
    employeeDependentsRelationshipId: number | null,
    isChild: boolean,
    isSpouse: boolean,
    description: string,
}