namespace Dominion.Core.Dto.Billing
{
    /// <summary>
    /// Billing description types. Mimics the dbo.BillingItemDescription table.
    /// </summary>
    public enum BillingItemDescriptionType
    {
        OneTimes                   = 1, 
        DeliveryWestMichigan       = 12,
        MailDelivery               = 19,
        LaserChecks                = 26,
        PayrollProcessing          = 27,
        PayrollChecks              = 28,
        DirectDeposit              = 29,
        FullServiceTaxFiling       = 30,
        EnvelopeStuffing           = 31,
        DeliveryService            = 32,
        Internet                   = 33,
        OfficialBankChecks         = 42,
        CheckSigning               = 43,
        EmployeeHistoryRecords     = 46,
        NewHires                   = 47,
        EmployeePersonnelChanges   = 48,
        TaxManagement              = 49,
        AdditionalFiling           = 53,
        BniDiscount                = 56,
        BasePayrollCharge          = 57,
        DirectDepositService       = 59,
        DeliveryGrandRapids        = 61,
        EarlyDelivery              = 63,
        HbaDiscount                = 71,
        SpecialPackaging           = 84,
        Discount                   = 89,
        SignatureReadyTaxFiling    = 90,
        W2Processing               = 95,
        PayrollTransaction         = 101,
        GeneralLedger              = 102,
        EmployeeSelfService        = 103,
        RetirementFileTransmission = 104,
        HrHelpline                 = 107,
        AttendanceOnDemand         = 108,
        TalxUnemploymentFile       = 109,
        CheckStock                 = 110,
        PayrollCredit              = 113,
        Reports                    = 114,
        SameDayProcessing          = 115,
        PrintBackFile              = 117,
        Handling                   = 119,
        TimeclockLease             = 120,
        DominionTimeAndAttendance  = 122,
        CheckReconFile             = 123,
        AtmUserAccounts            = 124,
        AtmPerEmployee             = 125,
        UsTelepunch                = 126,
        PayCards                   = 127,
        LeaveManagement            = 128,
        PositivePay                = 130,
        LaborSource                = 131,
        ApplicantTracking          = 132,
        ClockRental                = 133,
        PointsPolicy               = 138,
        BenefitAdministration      = 139,
        YearEndAdjustment          = 140,
        AcaReporting               = 141,
        NewClientSetup             = 142,
        ReportsOneTime             = 143,
        BillingOffset              = 144,
        Onboarding                 = 145,
        ExtendedAccess             = 146,
        CreditCarryOver            = 147,
        AcaPremium                 = 148,
        Essentials                 = 149,
        Professional               = 150,
        ProfessionalPlus           = 151,
        PerformanceManagement      = 152,
        Geofencing                 = 153,
        ActivationFee              = 154
    }
}
