export interface ClientGLAssignment {
    clientGLAssignmentId: number,
    generalLedgerTypeId: number,
    clientCostCenterId: number | null,
    clientGeneralLedgerId: number | null,
    foreignKeyId: number | null,
    description: string,
    clientId: number,
    modified: Date,
    modifiedBy: string,
    isAccrued: Boolean,
    isDetail: Boolean,
    isOffset: Boolean,
    sequenceNum: number | null,
    clientDepartmentId: number | null,
    project: string,
    clientDivisionId: number | null,
    clientGroupId: number | null,
    clientGLClassGroupId: number | null,
    canBeDetail: Boolean,
    canBeAccrued: Boolean,
    canBeOffset: Boolean,
    sequenceId: number
}