namespace Dominion.Core.Dto.User
{
    public enum OtherAccessClaimType : short
    {
        HasTimePolicy                               = 0,
        IsApplicantAdmin                            = 1,
        UserEmployeeSelfServiceOnly                 = 2,
        UserEmployeeOnly                            = 3,
        UserReportingOnly                           = 4,
        UserBlockPayrollAccess                      = 5,
        UserTimeClock                               = 6,
        IsAnonymous                                 = 7,
        HasApplicantRecord                          = 8,
        SupervisorAttachmentsAllowAddEdit           = 9,
        SupervisorAttachmentsEmployeeAccessOnly     = 10,
        SupervisorAttachmentsViewOnly               = 11,
        SupervisorFolderCannotCreateFolders         = 12,
        SupervisorFolderCreateAllFolders            = 13,
        SupervisorFolderCreateIndividualFoldersOnly = 14,
        UserViewHourlyRates                         = 15,
        UserViewSalaryRates                         = 16,
        UserViewHourlyEmployees                     = 17,
        UserViewSalaryEmployees                     = 18,
        SupervisorViewManagerLinks                  = 19,
        UserBlockHrAccess                           = 20,
        ClientEssOptionAllowImageUpload             = 21,
        SupervisorGroupPlannerAllowed               = 22,
        UserEmployeeIsActive                        = 23,
        SupervisorCanCertifyI9                      = 24,
        SupervisorAllowCompetencyModelAssignment    = 25,
        SupervisorViewOsha                          = 26,
        UserEmployeeSelfServiceViewOnly             = 27,
        UserEditGl                                  = 28,
        UserHasEmployee                             = 29,
        SupervisorCanAddEmployeesToOnboarding       = 30,
        IsBillingAdmin                              = 31,
        IsEmployeeNavigatorAdmin                    = 32,
        SupervisorAttachmentsAllowAdd               = 33,
    }
}