export interface IReportParameter {
    ClientId                       : number | null,
    EmployeeId                     : number | null,
    StateId                        : number | null,
    Quarter                        : string,
    Year                           : string,
    PayrollCheckSeqId              : number | null,
    SequenceId                     : number | null,
    PayrollId                      : number | null,
    OrderBy                        : string,
    TaxFrequencyId                 : number | null,
    GenPaycheckHistoryId           : number | null,
    ConsentType                    : string,
    WhoPrints                      : string,
    StartDate                      : Date | string | null,
    EndDate                        : Date | string | null,
    UniqueId                       : number | null,
    IsInterface                    : string,
    Order                          : string,
    UserId                         : number | null,
    UnemploymentId                 : number | null,
    ClientName                     : string,
    Selected                       : string,
    EmployeeStatus                 : string,
    EmployeePointsCode             : string,
    ClockClientPointExceptionId    : string,
    ClockClientPerfectAttendanceId : string,
    ViewableByEmployee             : string,
    IsPayrollSummary               : string,
    HideDetail                     : string,
    EmployeeTypeId                 : string,
    PayrollRemoteCheckFormatId     : string,
    checkDate                      : Date | null,
    GenVendorPaymentHistoryId      : string,
    Active                         : string,
    FilterCategory                 : string,
    FilterID                       : number | null,
    VendorType                     : string,
    ReturnFilterOnly               : Boolean,
    CsvChangeLogIds                : string,
    fileTypeId                     : number,
    fileFormatId                   : string
}